### GET Request
GET http://localhost:3050/api/users
content-type: application/json

### GET Request
GET http://localhost:3050/api/users/0aa5bbc4-1a9a-428f-a989-2e434605603c
content-type: application/json

### POST Request
POST http://localhost:3050/api/users
content-type: application/json

{
    "firstName": "New User",
    "lastName": "New New",
    "email": "jhoy@mail.mail",
    "phoneNumber": "066 000-00-00",
    "password": "333333"
}

### PUT Request
PUT http://localhost:3050/api/users/0aa5bbc4-1a9a-428f-a989-2e434605603c
content-type: application/json

{
    "firstName": "New User",
    "lastName": "New New User",
    "email": "newUser@mail.mail",
    "phoneNumber": "+38(066)0000000",
    "password": "333333"
}

### DELETE Request
DELETE http://localhost:3050/api/users/f4dde2ef-d36c-405b-8edf-87ad4197e6cb



### GET Request
GET http://localhost:3050/api/fighters
content-type: application/json

### GET Request
GET http://localhost:3050/api/fighters/3e31ecff-84f9-4f3f-99ca-a2889ec32d2a
content-type: application/json

### POST Request
POST http://localhost:3050/api/fighters
content-type: application/json

{
    "name": "New NewFighter",
    "health": 50,
    "power": 3,
    "defense": 5
}

### PUT Request
PUT http://localhost:3050/api/fighters/6bd98c72-26a1-4aea-8fcc-28c6705d7bb2
content-type: application/json

{
    "name": "New Fighter",
    "health": 50,
    "power": 3,
    "defense": 5
}

### DELETE Request
DELETE http://localhost:3050/api/fighters/0bf3b8a3-1972-4713-a46d-606cbeb3e3ce



### GET Request
GET http://localhost:3050/api/fights
content-type: application/json

### GET Request
GET http://localhost:3050/api/fights/896c5a13-6037-435b-b96e-66dd8c1712de
content-type: application/json

### POST Request
POST http://localhost:3050/api/fights
content-type: application/json

{
    "fighter1": "e251daf6-9954-4938-8111-6c35fceb9240",
    "fighter2": "3aab1a88-8104-40a9-81ea-aa102dfbf068",
    "log": [
      "1def3850-9f60-46db-acbe-a4ec96869cf3",
      "2021-01-16T16:49:33.348Z",
      27,
      23,
      18,
      -1
    ]
}

### PUT Request
PUT http://localhost:3050/api/fights/896c5a13-6037-435b-b96e-66dd8c1712de
content-type: application/json

{
    "fighter1": "3aab1a88-8104-40a9-81ea-aa102dfbf068",
    "fighter2": "e251daf6-9954-4938-8111-6c35fceb9240",
    "log": [
      "1def3850-9f60-46db-acbe-a4ec96869cf3",
      "2021-01-11T16:49:33.348Z",
      27,
      23,
      18,
      -1
    ]
}

### DELETE Request
DELETE http://localhost:3050/api/fights/896c5a13-6037-435b-b96e-66dd8c1712de